### ISSUE TITLE
Implement `queryWithNamed`

### ISSUE THREAD

**Issue by oishikg** [Holmusk/postgresql-simple-named#16]
Currently, the `PgNamed` library has no named parameter implementation for `queryWith`. Implementing a `queryWithNamed` would be very helpful, since we could use it as part of the refactoring in [this issue](https://github.com/Holmusk/CDMP/pull/863), and for future functions which need to use a user defined row parser.

**Comment by chshersh** [comment]
@oishikg You can open PR to this repo with the implementation of this function

**Comment by oishikg** [comment]
@chshersh , thanks for the comment, I've done this! See #17
