### ISSUE TITLE
Implement some tests

### ISSUE THREAD

**Issue by vrom911** [Holmusk/postgresql-simple-named#2]

**Comment by chshersh** [comment]
We have some examples in the documentation, so at least we can add `doctest`. However, if we want to check `IO` functions where we execute queries, then we need to do something on CI to run DB in `docker` image or something like that... Not sure how to do this, but can research and see whether it's possible or not.

**Comment by vrom911** [comment]
I was thinking also about a few unit test of parsing and replacing queries.
