### ISSUE TITLE
`PgNamedError` doesn't play nice with resource-pool

### ISSUE THREAD

**Issue by 2mol** [Holmusk/postgresql-simple-named#23]
How would I use this with `resource-pool`? Example:

```haskell
sqlExecuteN :: Pool Connection -> [PgNamed.NamedParam] -> Query -> IO Int64
sqlExecuteN pool params sqlStatement =
    Pool.withResource pool (\conn -> PgNamed.executeNamed conn sqlStatement params)
```

This doesn't compile because `GHC.IO.Exception.IOException` can't be matched with `PgNamed.PgNamedError`.

This constraint comes from `mtl-2.2.2:Control.Monad.Error.Class.MonadError`. Am I just missing a constraint in my type signature or can I derive th right instance for `PgNamed.PgNamedError`?

**Comment by vrom911** [comment]
You can see an example of how it is done in the `three-layer` repository:

https://github.com/Holmusk/three-layer/blob/1b58ec102f206681b66a584ca4a7d18f2eb4ef81/src/Lib/Db/Functions.hs#L99-L106

**Comment by 2mol** [comment]
Thank you very much for the answer. I need to pick the code apart a bit to understand what it does. I'm closing the issue, since it's more my own lack of understanding and not an issue of this lib.

**Comment by vrom911** [comment]
Feel free to ask more question if it's not clear from the code. We are using this library with `resource-pool` and it works great for us :slightly_smiling_face:
