### ISSUE TITLE
Allow usage of base-4.13.0.0

### ISSUE THREAD

**Issue by honungsburk** [Holmusk/postgresql-simple-named#25]
From reading the error messages in my project I've gathered that the base library available in a project is tied to the GHC version used. This project has the requirement >=4.11 && <4.13 
it doesn't work with the newer versions of GHC since they have version 4.13. Is it possible to bump it?

**Comment by turboMaCk** [comment]
Hello @honungsburk. Upper bound on base was relaxed in https://github.com/Holmusk/postgresql-simple-named/pull/24. We did not publish the new version though yet. Please use [stack.yaml](http://docs.haskellstack.org/en/stable/yaml_configuration/#packages) if you're stack user or `overrideAttrs` if you're nix user to pin `postgresql-simple-named` to current git head in mean time.

**Comment by honungsburk** [comment]
Thank you @turboMaCk for the quick response! I managed to add it to my dependencies.
