### ISSUE TITLE
Query errors out with JSONB operators

### ISSUE THREAD

**Issue by nitinprakash96** [Holmusk/postgresql-simple-named#30]
A couple of JSONB operators like `?|` and `?&` don't play nice with the library.
Notice how they seem to be interpreted as named parameters in the first query.

```haskell
-- @?|@ is probably being interpreted as a named parameter
> extractNames "SELECT foo FROM my_table WHERE (foo->'mood'->'tag_keys' ?| ?selectedTags);"
Left PostgreSQL named parameter error: Query contains an empty name: SELECT  foo FROM my_table WHERE (foo->'mood'->'tag_keys' ?| ?selectedTags);
>
-- @> works perfectly fine.Not that this query itself is correct. 
-- Just using it to enable some contrast with the above
> extractNames "SELECT foo FROM my_table WHERE (foo->'mood'->'tag_keys' @> ?selectedTags);"
Right ("SELECT foo FROM my_table WHERE (foo->'mood'->'tag_keys' @> ?);","selectedTags" :| [])
```

**Comment by turboMaCk** [comment]
nice examples. Yes the parsing of named arguments is rather naive at the moment.

https://github.com/Holmusk/postgresql-simple-named/blob/1a917ba0ada2e36a8f62fa8be3f120436ada65d1/src/PgNamed.hs#L103-L139

but I think there might be simple solution to work around the example operators by just making this https://github.com/Holmusk/postgresql-simple-named/blob/master/src/PgNamed.hs#L131-L132 more intelligent

**Comment by nitinprakash96** [comment]
postgres-simple did something like this https://github.com/haskellari/postgresql-simple/commit/6e30ae70ca2d4913f3da84744a50d9a3a7b3f911

**Comment by nitinprakash96** [comment]
We can probably add a helper function something like this:
```haskell
-- Check if character is reserved by postgres
-- If it is, them prohibit from using as a named parameter
-- Eg: @?|@ is a JSONB operator reserved by postgres and should
-- not be considered as a named parameter
isReservedOp :: Char -> Bool
isReservedOp c = c `elem` ['|', '&']
```

and use if with
```haskell
isNameChar :: Char -> Bool
-- currently, @_@ is being overlooked. We can maybe add it to the list of reserved operators? Don't know yet.
isNameChar c = isAlphaNum c || isReservedOp c || c == '_'
```
Thoughts @jhrcek @turboMaCk ?

**Comment by jhrcek** [comment]
I'm not sure.
My expectation would be that if ?| or other built-in postgres operator is in the query, it should not be considered "named parameter" at all, just ignored.

What we want is basically a lexer that allows us to distinguish between 3 states:
1. ? that is part of name (should lead to name being extracted)
2. ? that is part of some existing operator (should be ignored)
3. ? used in an invalid way which doesn't correspond to 1 and 2 (should fail with NameError)

This is the kind of thing I'd develop in TDD way - first find all postgres operators that canstart with ?, extand the test suite and the solution will fall out of that :)
