### ISSUE TITLE
Upload the current version to Hackage

### ISSUE THREAD

**Issue by chshersh** [Holmusk/postgresql-simple-named#36]
The version of `postgresql-simple-named` library from `master` supports GHC 8.10 and GHC 9.0. It would be nice to have it uploaded to Hackage 🤗 

> I still have Hackage upload access for this library so I can prepare the changelog and upload the new version to Hackage if this is more convenient to you.

**Comment by nitinprakash96** [comment]
Sorry I completely forgot to upload. Will do asap.

**Comment by nitinprakash96** [comment]
@chshersh Done!

**Comment by chshersh** [comment]
@nitinprakash96 Thanks a lot! ❤️
